import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import Navber from "@/components/Navber";
import Footer from "@/components/Footer";

const poppins = Poppins({
  variable: "--font-poppins", // Spelling thik kora hoyeche
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"]
});


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <body className={`${poppins.className} min-h-full flex flex-col`}>
        <Navber></Navber>
        <main>{children}</main>
        <Footer></Footer>
        
        </body>
    </html>
  );
}
